/*
* If not stated otherwise in this file or this component's LICENSE file the
* following copyright and licenses apply:
*
* Copyright 2011 RDK Management
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef DOCSDEVEVENTTABLE_H
#define DOCSDEVEVENTTABLE_H

#include <vector>
#include <string>
//#include "pfcmutex.h"
#include "docsDevEventTable_enums.h"
using namespace std;
/*
 * function declarations 
 */
void            init_docsDevEventTable(void);
void            initialize_table_docsDevEventTable(void);
Netsnmp_Node_Handler docsDevEventTable_handler;
NetsnmpCacheLoad docsDevEventTable_load;
NetsnmpCacheFree docsDevEventTable_free;
//vector<docsDevEventTable_t> docsEventTableList;
int docsDevEventTable_createEntry_allData(netsnmp_tdata * table_data, docsDevEventTable_t *ListDoscEvent);
extern "C" void vlSnmpDocsEventTable_ResetLog();

#define DOCSDEVEVENTTABLE_TIMEOUT  4

/*
 * column number definitions for table docsDevEventTable 
 */
#define COLUMN_DOCSDEVEVINDEX        1
#define COLUMN_DOCSDEVEVFIRSTTIME        2
#define COLUMN_DOCSDEVEVLASTTIME        3
#define COLUMN_DOCSDEVEVCOUNTS        4
#define COLUMN_DOCSDEVEVLEVEL        5
#define COLUMN_DOCSDEVEVID        6
#define COLUMN_DOCSDEVEVTEXT        7
#endif                          /* DOCSDEVEVENTTABLE_H */
