/*
* If not stated otherwise in this file or this component's LICENSE file the
* following copyright and licenses apply:
*
* Copyright 2011 RDK Management
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef DOCSDEVEVCONTROLTABLE_H
#define DOCSDEVEVCONTROLTABLE_H

#include "docsDevEventTable_enums.h"
/*
 * function declarations 
 */
void            init_docsDevEvControlTable(void);
void            initialize_table_docsDevEvControlTable(void);
Netsnmp_Node_Handler docsDevEvControlTable_handler;
NetsnmpCacheLoad docsDevEvControlTable_load;
NetsnmpCacheFree docsDevEvControlTable_free;

int docsDevEvControlTable_createEntry_allData(netsnmp_tdata * table_data, int priority , int ListdocsDevEvControl, int count);

extern "C" int vl_docsDevEvControlTable_get_reporting_method(int priority);
extern "C" int vl_docsDevEvControlTable_SET_reporting_method(int priority, int eDocsDevEvReportingVal);

#define DOCSDEVEVCONTROLTABLE_TIMEOUT  4

/*
 * column number definitions for table docsDevEvControlTable 
 */
#define COLUMN_DOCSDEVEVPRIORITY        1
#define COLUMN_DOCSDEVEVREPORTING        2



#endif                          /* DOCSDEVEVCONTROLTABLE_H */
