/*
* If not stated otherwise in this file or this component's LICENSE file the
* following copyright and licenses apply:
*
* Copyright 2011 RDK Management
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_enums.conf 12909 2005-09-29 22:16:22Z hardaker $
 */
#ifndef HOST_ENUMS_H
#define HOST_ENUMS_H

/*
 * enums for column hrDeviceStatus 
 */
#define HRDEVICESTATUS_UNKNOWN        1
#define HRDEVICESTATUS_RUNNING        2
#define HRDEVICESTATUS_WARNING        3
#define HRDEVICESTATUS_TESTING        4
#define HRDEVICESTATUS_DOWN        5

/*
 * enums for column hrPrinterStatus 
 */
#define HRPRINTERSTATUS_OTHER        1
#define HRPRINTERSTATUS_UNKNOWN        2
#define HRPRINTERSTATUS_IDLE        3
#define HRPRINTERSTATUS_PRINTING        4
#define HRPRINTERSTATUS_WARMUP        5

/*
 * enums for column hrDiskStorageAccess 
 */
#define HRDISKSTORAGEACCESS_READWRITE        1
#define HRDISKSTORAGEACCESS_READONLY        2

/*
 * enums for column hrDiskStorageMedia 
 */
#define HRDISKSTORAGEMEDIA_OTHER        1
#define HRDISKSTORAGEMEDIA_UNKNOWN        2
#define HRDISKSTORAGEMEDIA_HARDDISK        3
#define HRDISKSTORAGEMEDIA_FLOPPYDISK        4
#define HRDISKSTORAGEMEDIA_OPTICALDISKROM        5
#define HRDISKSTORAGEMEDIA_OPTICALDISKWORM        6
#define HRDISKSTORAGEMEDIA_OPTICALDISKRW        7
#define HRDISKSTORAGEMEDIA_RAMDISK        8

/*
 * enums for column hrDiskStorageRemoveble 
 */
#define HRDISKSTORAGEREMOVEBLE_TRUE        1
#define HRDISKSTORAGEREMOVEBLE_FALSE        2

/*
 * enums for column hrFSAccess 
 */
#define HRFSACCESS_READWRITE        1
#define HRFSACCESS_READONLY        2

/*
 * enums for column hrFSBootable 
 */
#define HRFSBOOTABLE_TRUE        1
#define HRFSBOOTABLE_FALSE        2

/*
 * enums for column hrSWRunType 
 */
#define HRSWRUNTYPE_UNKNOWN        1
#define HRSWRUNTYPE_OPERATINGSYSTEM        2
#define HRSWRUNTYPE_DEVICEDRIVER        3
#define HRSWRUNTYPE_APPLICATION        4

/*
 * enums for column hrSWRunStatus 
 */
#define HRSWRUNSTATUS_RUNNING        1
#define HRSWRUNSTATUS_RUNNABLE        2
#define HRSWRUNSTATUS_NOTRUNNABLE        3
#define HRSWRUNSTATUS_INVALID        4

/*
 * enums for column hrSWInstalledType 
 */
#define HRSWINSTALLEDTYPE_UNKNOWN        1
#define HRSWINSTALLEDTYPE_OPERATINGSYSTEM        2
#define HRSWINSTALLEDTYPE_DEVICEDRIVER        3
#define HRSWINSTALLEDTYPE_APPLICATION        4


#endif                          /* HOST_ENUMS_H */
