/*
* If not stated otherwise in this file or this component's LICENSE file the
* following copyright and licenses apply:
*
* Copyright 2011 RDK Management
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef SNMPTARGETADDREXTTABLE_H
#define SNMPTARGETADDREXTTABLE_H
#include "ocStbHostMibModule.h"

/*
 * function declarations 
 */
void            init_snmpTargetAddrExtTable(void);
void            initialize_table_snmpTargetAddrExtTable(void);
Netsnmp_Node_Handler snmpTargetAddrExtTable_handler;
NetsnmpCacheLoad snmpTargetAddrExtTable_load;
NetsnmpCacheFree snmpTargetAddrExtTable_free;
int snmpTargetAddrExtTable_createEntry_allData(netsnmp_tdata * table_data, struct VL_TLV_TRANSPORT_ADDR_AND_MASK & TargetExtaddr, int count);
int snmpTargetAddrExtTable_createEntry_allData(netsnmp_tdata * table_data, struct v3NotificationReceiver_t & rReceiver, int count);
#define SNMPTARGETADDREXTTABLE_TIMEOUT  2

/*
 * column number definitions for table snmpTargetAddrExtTable 
 */
#define COLUMN_SNMPTARGETADDRTMASK        1
#define COLUMN_SNMPTARGETADDRMMS        2
#endif                          /* SNMPTARGETADDREXTTABLE_H */
