/*
* If not stated otherwise in this file or this component's LICENSE file the
* following copyright and licenses apply:
*
* Copyright 2011 RDK Management
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef VACMVIEWTREEFAMILYTABLE_H
#define VACMVIEWTREEFAMILYTABLE_H

/*
 * function declarations 
 */
void            init_vacmViewTreeFamilyTable(void);
void            initialize_table_vacmViewTreeFamilyTable(void);
Netsnmp_Node_Handler vacmViewTreeFamilyTable_handler;
NetsnmpCacheLoad vacmViewTreeFamilyTable_load;
NetsnmpCacheFree vacmViewTreeFamilyTable_free;
int vacmViewTreeFamilyTable_createEntry_allData(netsnmp_tdata *table_data,int count, char *acessviewnameV3,char* oidSubtree , char *acessMax, int accessviewtype);
#define VACMVIEWTREEFAMILYTABLE_TIMEOUT  10

/*
 * column number definitions for table vacmViewTreeFamilyTable 
 */
#define COLUMN_VACMVIEWTREEFAMILYVIEWNAME        1
#define COLUMN_VACMVIEWTREEFAMILYSUBTREE        2
#define COLUMN_VACMVIEWTREEFAMILYMASK        3
#define COLUMN_VACMVIEWTREEFAMILYTYPE        4
#define COLUMN_VACMVIEWTREEFAMILYSTORAGETYPE        5
#define COLUMN_VACMVIEWTREEFAMILYSTATUS        6


//#ifndef VACMVIEWTREEFAMILYTABLE_ENUMS_H
//#define VACMVIEWTREEFAMILYTABLE_ENUMS_H

/*
 * enums for column vacmViewTreeFamilyType 
 */
#define VACMVIEWTREEFAMILYTYPE_INCLUDED        1
#define VACMVIEWTREEFAMILYTYPE_EXCLUDED        2

/*
 * enums for column vacmViewTreeFamilyStorageType 
 */
#define VACMVIEWTREEFAMILYSTORAGETYPE_OTHER        1
#define VACMVIEWTREEFAMILYSTORAGETYPE_VOLATILE        2
#define VACMVIEWTREEFAMILYSTORAGETYPE_NONVOLATILE        3
#define VACMVIEWTREEFAMILYSTORAGETYPE_PERMANENT        4
#define VACMVIEWTREEFAMILYSTORAGETYPE_READONLY        5

/*
 * enums for column vacmViewTreeFamilyStatus 
 */
#define VACMVIEWTREEFAMILYSTATUS_ACTIVE        1
#define VACMVIEWTREEFAMILYSTATUS_NOTINSERVICE        2
#define VACMVIEWTREEFAMILYSTATUS_NOTREADY        3
#define VACMVIEWTREEFAMILYSTATUS_CREATEANDGO        4
#define VACMVIEWTREEFAMILYSTATUS_CREATEANDWAIT        5
#define VACMVIEWTREEFAMILYSTATUS_DESTROY        6


//#endif                          /* VACMVIEWTREEFAMILYTABLE_ENUMS_H */



#endif                          /* VACMVIEWTREEFAMILYTABLE_H */
