/*
* If not stated otherwise in this file or this component's LICENSE file the
* following copyright and licenses apply:
*
* Copyright 2011 RDK Management
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef VACMSECURITYTOGROUPTABLE_H
#define VACMSECURITYTOGROUPTABLE_H

/*
 * function declarations 
 */
void            init_vacmSecurityToGroupTable(void);
void            initialize_table_vacmSecurityToGroupTable(void);
Netsnmp_Node_Handler vacmSecurityToGroupTable_handler;
NetsnmpCacheLoad vacmSecurityToGroupTable_load;
NetsnmpCacheFree vacmSecurityToGroupTable_free;
int vacmSecurityToGroupTable_createEntry_allData(netsnmp_tdata *table_data, int count, int secmodel);
#define VACMSECURITYTOGROUPTABLE_TIMEOUT  10



/*
 * column number definitions for table vacmSecurityToGroupTable 
 */
#define COLUMN_VACMSECURITYMODEL        1
#define COLUMN_VACMSECURITYNAME        2
#define COLUMN_VACMGROUPNAME        3
#define COLUMN_VACMSECURITYTOGROUPSTORAGETYPE        4
#define COLUMN_VACMSECURITYTOGROUPSTATUS        5


//#ifndef VACMSECURITYTOGROUPTABLE_ENUMS_H
//#define VACMSECURITYTOGROUPTABLE_ENUMS_H

/*
 * enums for column vacmSecurityToGroupStorageType 
 */
#define VACMSECURITYTOGROUPSTORAGETYPE_OTHER        1
#define VACMSECURITYTOGROUPSTORAGETYPE_VOLATILE        2
#define VACMSECURITYTOGROUPSTORAGETYPE_NONVOLATILE        3
#define VACMSECURITYTOGROUPSTORAGETYPE_PERMANENT        4
#define VACMSECURITYTOGROUPSTORAGETYPE_READONLY        5

/*
 * enums for column vacmSecurityToGroupStatus 
 */
#define VACMSECURITYTOGROUPSTATUS_ACTIVE        1
#define VACMSECURITYTOGROUPSTATUS_NOTINSERVICE        2
#define VACMSECURITYTOGROUPSTATUS_NOTREADY        3
#define VACMSECURITYTOGROUPSTATUS_CREATEANDGO        4
#define VACMSECURITYTOGROUPSTATUS_CREATEANDWAIT        5
#define VACMSECURITYTOGROUPSTATUS_DESTROY        6
//#endif                          /* VACMSECURITYTOGROUPTABLE_ENUMS_H */


#endif                          /* VACMSECURITYTOGROUPTABLE_H */

