/*
* If not stated otherwise in this file or this component's LICENSE file the
* following copyright and licenses apply:
*
* Copyright 2013 RDK Management
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/ 
 

#ifndef POD_SERVER_H
#define POD_SERVER_H
#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include "rmf_error.h"

#define POD_SERVER_CMD_DFLT_PORT_NO 50506
#define POD_HAL_SERVICE_CMD_DFLT_PORT_NO 50509

typedef enum 
{
	POD_SERVER_CMD_START_DECRYPT,
	POD_SERVER_CMD_STOP_DECRYPT,
	POD_SERVER_CMD_GET_CASYSTEMID,
	POD_SERVER_CMD_CONFIG_CIPH,
	POD_SERVER_CMD_GETMAX_ELM_STR,
	POD_SERVER_CMD_HB,
	POD_SERVER_CMD_IS_READY,
	POD_SERVER_CMD_POLL_EVENT,
	POD_SERVER_CMD_POLL_SIMGR_EVENT,
	POD_SERVER_CMD_REGISTER_CLIENT,
	POD_SERVER_CMD_UNREGISTER_CLIENT,
	POD_SERVER_CMD_REGISTER_SIMGR_CLIENT,	
	POD_SERVER_CMD_UNREGISTER_SIMGR_CLIENT,
	POD_SERVER_CMD_GET_CCI_BIT,
	POD_SERVER_CMD_GET_PROGRAM_INFO,
	POD_SERVER_CMD_GET_PROGRAM_INFO_BY_VCN,	

	POD_SERVER_CMD_GET_SYSTEM_IDS,
	POD_SERVER_CMD_GET_VIRTUAL_CHANNEL_NUMBER,


	POD_SERVER_CMD_GET_SYSTIME,
	POD_SERVER_CMD_GET_TIMEZONE,

	POD_SERVER_CMD_DUMP_DSG_STAT,	
	POD_SERVER_CMD_DSG_CHECKANDRECOVER_CONNECTIVITY,		
	POD_SERVER_CMD_CDL_UPGRADE_TO_IMAGE,	
	POD_SERVER_CMD_START_HOMING_DOWNLOAD,	


	POD_SERVER_CMD_GET_CCI_INFO_ELEMENT,
	POD_SERVER_CMD_GET_CP_ID_LIST,
	POD_SERVER_CMD_GET_CP_KEY_GEN_REQUEST,
	POD_SERVER_CMD_GET_CP_CCI_CHALLENGE_COUNT,
	POD_SERVER_CMD_GET_CP_CERT_STATUS,
	POD_SERVER_CMD_GET_CP_AUTH_KEY_STATUS,
	POD_SERVER_CMD_GET_VCT_ID,
	POD_SERVER_CMD_GET_EAS_LOCATION,
	POD_SERVER_CMD_GET_GEN_FEATURE_DATA,
	POD_SERVER_CMD_SET_DSG_CONFIG,
	POD_SERVER_CMD_GET_DST_EXIT,
	POD_SERVER_CMD_GET_DST_ENTRY,
	POD_SERVER_CMD_GET_DST_DELTA,
	POD_SERVER_CMD_DUMP_BUFFER,
	POD_SERVER_CMD_GET_GEN_TIME_ZONE_OFFSET,
	POD_SERVER_CMD_GET_GEN_RESOURCE_ID,
	POD_SERVER_CMD_GET_INBAND_OOB_MODE,
	POD_SERVER_CMD_GET_APP_INFO,
	POD_SERVER_CMD_GET_DSG_ETH_INFO,
	POD_SERVER_CMD_GET_CHANNEL_MAPID,
	POD_SERVER_CMD_GET_DACID,
	POD_SERVER_CMD_GET_LOST_DSG_IPU_INFO,
	POD_SERVER_CMD_GET_IPV6_SUBMASK,
	POD_SERVER_CMD_SET_ECM_ROUTE,
	POD_SERVER_CMD_GET_RC_IPADDRESS,
	POD_SERVER_CMD_GET_DSG_IP_INFO,
	POD_SERVER_CMD_GET_DSG_IP,
	POD_SERVER_CMD_GET_CCAPP_INFO,
	POD_SERVER_CMD_GET_DSG_CABLE_CARD_INFO,
	POD_SERVER_CMD_GET_HOST_CABLE_CARD_INFO,
	POD_SERVER_CMD_GET_HOST_ID_LUHN,
	POD_SERVER_CMD_CDL_HOST_FW_STATUS,
	POD_SERVER_CMD_CDL_HOST_FW_STATUS_CHECK,
	POD_SERVER_CMD_IS_DSG_MODE,
	POD_SERVER_CMD_HALSYS_SNMP_REQUEST,
	POD_SERVER_CMD_GET_SOCKET_FLOW_COUNT,
	POD_SERVER_CMD_SEND_CARD_MIB_ACC_SNMP_REQ,
	POD_SERVER_CMD_GET_STB_HOST_ID,
	POD_SERVER_CMD_GET_CABLE_CARD_CERT_INFO,
	POD_SERVER_CMD_GET_HOST_SECURITY_ID,
	POD_SERVER_CMD_GET_APP_INFO_WITH_PAGES,
	POD_SERVER_CMD_GET_NUMBER_OF_CC_APPS,
	POD_SERVER_CMD_UPDATE_TIME_EXT,
	POD_SERVER_CMD_GET_CABLE_CARD_VERSION,	
	POD_SERVER_CMD_NOTIFY_SAS_TERMINATION,	


	/* Dont change below values as it is used by CANH Java process */
	POD_SERVER_CMD_GET_MANUFACTURER_ID = 0x00A9,
	POD_SERVER_CMD_SEND_APDU = 0x00AA,
	POD_SERVER_CMD_RCV_APDU = 0x00AB,	
	POD_SERVER_CMD_SAS_CONNECT = 0x00AC,
        POD_SERVER_CMD_STB_REBOOT = 0x00AD,

	/* the below entry is required for USE_IPDIRECT_UNICAST and so adding this as last entry to avoid conflict */
	POD_SERVER_CMD_START_INBAND_TUNE,
	POD_SERVER_CMD_GET_CC_VERSION,
}POD_SERVER_CMD;

typedef enum 
{
	POD_HAL_SERVER_CMD_CONFIG_CIPHER,
	POD_HAL_SERVER_CMD_GET_TUNER_INFO,
	POD_HAL_SERVER_CMD_GET_TUNER_COUNT,
	POD_HAL_SERVER_CMD_GET_PACE_TUNER_INFO,			
	POD_HAL_SERVER_CMD_CONFIG_TIMEZONE,
	POD_HAL_SERVER_CMD_CONFIG_TIMEOFDAY,
}POD_HAL_SERVER_CMD;


typedef enum 
{
	POD_RESP_NO_EVENT,
	POD_RESP_GEN_EVENT,
	POD_RESP_CORE_EVENT,
	POD_RESP_DECRYPT_EVENT,	
	POD_RESP_TIMEZONE_SET_EVENT,
	POD_RESP_SYSTIME_SET_EVENT,
}POD_SERVER_RESPONSE;

rmf_Error podServerStart(	);
rmf_Error podServerStop(	);


#ifdef __cplusplus
}
#endif
#endif


